/**
 * flascc.c
 * This file exists because we need to have a consistent name in the compiled .o file.
 * View the object names with "nm flascc.o"

 * Generated by ARK2D Framework.
 */

#ifndef FLASCC_GLUE_H_
#define FLASCC_GLUE_H_

	#if defined(ARK2D_FLASCC)

		#include "ARK.h"

	 	void flascc_tick() {
			ARK2D::getContainer()->m_platformSpecific.doTick();
		}

		void flascc_event_mouseDown(int button, int x, int y) {
			GameContainer* container = ARK2D::getContainer();

			float thisx = (float) x;
			float thisy = (float) y;
			thisx -= container->getTranslateX();
			thisy -= container->getTranslateY();

			thisx /= container->getScale();
			thisy /= container->getScale();

			unsigned int key = Input::MOUSE_BUTTON_LEFT;
			if (button == 0) {
				key = Input::MOUSE_BUTTON_LEFT;
			} else if (button == 1) {
				key = Input::MOUSE_BUTTON_RIGHT;
			}

			Input* i = ARK2D::getInput();
			i->mouse_x = (int) thisx;
			i->mouse_y = (int) thisy;
			i->pressKey(key);
		}

		void flascc_event_mouseMoved(int x, int y) {
			GameContainer* container = ARK2D::getContainer();

			float thisx = (float) x;
			float thisy = (float) y;
			
			thisx -= container->getTranslateX();
			thisy -= container->getTranslateY();

			thisx /= container->getScale();
			thisy /= container->getScale();

			Input* i = ARK2D::getInput();
			ARK2D::getGame()->mouseMoved((int) thisx, (int) thisy, i->mouse_x, i->mouse_y);
			i->mouse_x = (int) thisx;
			i->mouse_y = (int) thisy;
		}

		void flascc_event_mouseUp(int button, int x, int y) {
			GameContainer* container = ARK2D::getContainer();

			float thisx = (float) x;
			float thisy = (float) y;
			thisx -= container->getTranslateX();
			thisy -= container->getTranslateY();

			thisx /= container->getScale();
			thisy /= container->getScale();

			unsigned int key = Input::MOUSE_BUTTON_LEFT;
			if (button == 0) {
				key = Input::MOUSE_BUTTON_LEFT;
			} else if (button == 1) {
				key = Input::MOUSE_BUTTON_RIGHT;
			}

			Input* i = ARK2D::getInput();
			i->mouse_x = (int) thisx;
			i->mouse_y = (int) thisy;
			i->releaseKey(key);
		}

		void flascc_event_keyDown(int key) {
			 // key code mapping?
			ARK2D::getInput()->pressKey(key);
		}

		void flascc_event_keyUp(int key) {
			ARK2D::getInput()->releaseKey(key);
		}

	#endif

#endif
